version: 2.1
orbs:
  orb-tools: circleci/orb-tools@volatile
  ghostinspector: ghostinspector/test-runner@dev:02

# publish dev orb
# - can this be referenced inline
# test against orb scenarios
# [x] better info for bad API key -> orb will complain about key missing if not in env
# [ ] debug?
# [ ] startUrl
# [ ] extraParams
# publish prod orb

jobs:
  execute-test-orb:
    executor: ghostinspector/default
    steps:
      - ghostinspector/execute-test:
          start-url: https://ghostinspector.com/
          id: 5bdb20218faf2b12926dd9c9
          extra-params: '{"paramOne": "expected value 1", "paramTwo": "expected value 2"}'
          wait: true
      - ghostinspector/execute-suite:
          start-url: https://ghostinspector.com/
          id: 5bdb1f808faf2b12926dcd62
          extra-params: '{"paramOne": "expected value 1", "paramTwo": "expected value 2"}'
          wait: true

workflows:
  test:
    jobs:
      - execute-test-orb
